import Menu from '@/components/Menu'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gray-100"}>
        <div className='grid grid-cols-12'>
          <Menu />
          <div className='col-span-10 h-screen p-2 overflow-auto'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
